### ISSUE TITLE
Performance warnings

### ISSUE THREAD

**Issue by spekulatius** [MasterOfTheTiger/reimagine-twitter#12]
Hello @MasterOfTheTiger 

I get performance warnings ("this extension is slowing down a tab, would you like to deactivate it") quite often. Is there anything I can do to avoid this?

Peter

**Comment by MasterOfTheTiger** [comment]
There's not much I can do about this except report it upstream (but remember that there's no support for Firefox officially).

**Comment by spekulatius** [comment]
Yeah, I thought so. Still wanted to give it a try. Thanks!
