### ISSUE TITLE
Please add link to the extension

### ISSUE THREAD

**Issue by divyanshu013** [MasterOfTheTiger/reimagine-twitter#8]
Hi, thanks for maintaining a fork. I think it would be great to have a direct link to the extension https://addons.mozilla.org/en-US/firefox/addon/reimagined-twitter/

**Comment by MasterOfTheTiger** [comment]
Oh. Thank you very much. I recently redid the whole repo, and I must have forgotten to re-add it.

**Comment by MasterOfTheTiger** [comment]
This is fixed in 2777f57e9675873e9640958c052444ede2c6ad2b
