### ISSUE TITLE
Settings are not persisted

### ISSUE THREAD

**Issue by ThibaultVlacich** [MasterOfTheTiger/reimagine-twitter#9]
When changing the settings to activate / deactivate some features, the settings are not persisted when quitting Firefox. Everything is reset to the default settings when Firefox is restarted.

**Comment by MasterOfTheTiger** [comment]
Does this happen in the Chrome version? 

If not, it may be the way Firefox handles the way that the developers of refined Twitter designed the save feature. I will see what the problem is.

**Comment by ThibaultVlacich** [comment]
It seems to have been a one time bug, the settings has been persisted since my initial report.

I'm closing for now.

**Comment by MasterOfTheTiger** [comment]
Okay. If the issue happens again. Please reopen.
